#!/usr/bin/env bash
set -euo pipefail

# run-servers.sh
# Builds the React (Vite) app to a static dist/, starts the Node API server,
# and configures nginx to serve the static files on port 80 and proxy
# /api/* to the Node server.
# Writes logs and pids to ./logs.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="$ROOT_DIR/logs"
NGINX_CONF="$LOG_DIR/nginx-pridemap.conf"
mkdir -p "$LOG_DIR"

SERVER_DIR="$ROOT_DIR/server"
CLIENT_DIR="$ROOT_DIR/client/pridemap"
CLIENT_DIST="$CLIENT_DIR/dist"

# Allow overriding ports via environment
SERVER_PORT="${SERVER_PORT:-3001}"
NGINX_PORT="${NGINX_PORT:-80}"

# Allow running only the install/build step for testing: ./run-servers.sh --install-only
INSTALL_ONLY=false
if [[ "${1:-}" == "--install-only" ]]; then
  INSTALL_ONLY=true
fi

run_npm_install_if_needed() {
  local dir="$1"
  local label="$2"
  local install_log="$LOG_DIR/${label}-install.log"

  if [[ ! -d "$dir/node_modules" ]]; then
    if ! command -v npm >/dev/null 2>&1; then
      echo "npm is not installed or not on PATH; cannot install dependencies for $label"
      return 1
    fi
    echo "Installing npm dependencies for $label (this may take a minute)..."
    (cd "$dir" && npm install --silent) > "$install_log" 2>&1 || {
      echo "npm install failed for $label — see $install_log"
      return 1
    }
    echo "Installed $label dependencies; log: $install_log"
  else
    echo "Dependencies for $label appear present (node_modules exists)."
  fi
}

echo "Checking and installing dependencies if needed..."
run_npm_install_if_needed "$SERVER_DIR" server || true
run_npm_install_if_needed "$CLIENT_DIR" client || true

build_client() {
  echo "Building React app (npm run build)..."
  (cd "$CLIENT_DIR" && npm run build) > "$LOG_DIR/client-build.log" 2>&1 && {
    echo "Client build succeeded. Output: $CLIENT_DIST"
  } || {
    echo "Client build FAILED — see $LOG_DIR/client-build.log"
    tail -n 30 "$LOG_DIR/client-build.log"
    return 1
  }
}

build_client || true

# ---------------------------------------------------------------------------
# nginx setup
# ---------------------------------------------------------------------------

setup_nginx() {
  # Install nginx if not present
  if ! command -v nginx >/dev/null 2>&1; then
    echo "nginx not found — attempting to install..."
    if command -v apt-get >/dev/null 2>&1; then
      sudo apt-get install -y nginx
    elif command -v dnf >/dev/null 2>&1; then
      sudo dnf install -y nginx
    elif command -v yum >/dev/null 2>&1; then
      sudo yum install -y nginx
    elif command -v brew >/dev/null 2>&1; then
      brew install nginx
    else
      echo "Cannot install nginx automatically — no supported package manager found."
      echo "Please install nginx manually and re-run this script."
      return 1
    fi
  else
    echo "nginx is already installed: $(nginx -v 2>&1)"
  fi

  # Write the site config
  cat > "$NGINX_CONF" <<NGINXCONF
# pride-map nginx config
# Generated by run-servers.sh — do not edit by hand.
#
# Traffic flow:
#   Browser → nginx :${NGINX_PORT}
#     /api/*  → Node/Express  :${SERVER_PORT}  (strips /api prefix)
#     /*      → static files from $CLIENT_DIST

server {
    listen ${NGINX_PORT};
    server_name localhost;

    access_log $LOG_DIR/nginx-access.log;
    error_log  $LOG_DIR/nginx-error.log;

    # --- API proxy (Node/Express) ---
    location /api/ {
        proxy_pass         http://127.0.0.1:${SERVER_PORT}/;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }

    # --- React static build ---
    location / {
        root  $CLIENT_DIST;
        index index.html;
        # SPA fallback: any unknown path serves index.html so React Router works
        try_files \$uri \$uri/ /index.html;
    }
}
NGINXCONF

  echo "nginx config written to: $NGINX_CONF"

  # Validate the config
  if ! nginx -t -c "$NGINX_CONF" 2>/dev/null; then
    # nginx -t needs a full config; use include approach via a temp wrapper
    local tmp_conf
    tmp_conf="$(mktemp /tmp/nginx-test-XXXXXX.conf)"
    cat > "$tmp_conf" <<WRAPPER
events {}
http {
    include $NGINX_CONF;
}
WRAPPER
    if ! nginx -t -c "$tmp_conf" 2>&1 | tee -a "$LOG_DIR/nginx-error.log"; then
      echo "nginx config validation failed — check $LOG_DIR/nginx-error.log"
      rm -f "$tmp_conf"
      return 1
    fi
    rm -f "$tmp_conf"
  fi

  # Stop any existing nginx process using our config, then start fresh
  stop_nginx || true

  # Determine whether we need sudo (port < 1024 needs root on Linux)
  local nginx_cmd="nginx"
  if [[ "$NGINX_PORT" -lt 1024 ]] && [[ "$(id -u)" -ne 0 ]]; then
    nginx_cmd="sudo nginx"
  fi

  # Build a minimal wrapper config so nginx can run without needing /etc/nginx/nginx.conf
  local run_conf
  run_conf="$(mktemp /tmp/nginx-run-XXXXXX.conf)"
  # Determine a safe pid file path
  local nginx_pid_file="$LOG_DIR/nginx.pid"
  cat > "$run_conf" <<WRAPPER
pid $nginx_pid_file;
events { worker_connections 1024; }
http {
    include $NGINX_CONF;
}
WRAPPER

  echo "Starting nginx (port $NGINX_PORT)..."
  $nginx_cmd -c "$run_conf" 2>&1 | tee -a "$LOG_DIR/nginx-error.log" || {
    echo "Failed to start nginx — check $LOG_DIR/nginx-error.log"
    rm -f "$run_conf"
    return 1
  }
  # Store the wrapper path so we can reload/stop it later
  echo "$run_conf" > "$LOG_DIR/nginx-run-conf.path"
  echo "nginx started. Access the app at http://localhost:${NGINX_PORT}/"
}

stop_nginx() {
  local nginx_pid_file="$LOG_DIR/nginx.pid"
  local run_conf_path_file="$LOG_DIR/nginx-run-conf.path"

  if [[ -f "$nginx_pid_file" ]]; then
    local pid
    pid=$(cat "$nginx_pid_file" 2>/dev/null || true)
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      echo "Stopping nginx (PID $pid)..."
      local run_conf=""
      [[ -f "$run_conf_path_file" ]] && run_conf=$(cat "$run_conf_path_file" 2>/dev/null || true)
      if [[ -n "$run_conf" ]] && [[ -f "$run_conf" ]]; then
        if [[ "$(id -u)" -ne 0 ]] && [[ "$NGINX_PORT" -lt 1024 ]]; then
          sudo nginx -c "$run_conf" -s quit 2>/dev/null || sudo kill "$pid" 2>/dev/null || true
        else
          nginx -c "$run_conf" -s quit 2>/dev/null || kill "$pid" 2>/dev/null || true
        fi
        rm -f "$run_conf" "$run_conf_path_file"
      else
        kill "$pid" 2>/dev/null || true
      fi
    fi
    rm -f "$nginx_pid_file"
  fi
}

if [[ "$INSTALL_ONLY" == true ]]; then
  echo "--install-only flag provided; exiting after installs."
  exit 0
fi

start_node_server() {
  echo "Starting Node server (port $SERVER_PORT)..."
  ( cd "$SERVER_DIR" && PORT="$SERVER_PORT" node server.js ) > "$LOG_DIR/server.log" 2>&1 &
  SERVER_PID=$!
  echo "$SERVER_PID" > "$LOG_DIR/server.pid"
}

start_servers() {
  start_node_server
  echo "Launched Node server PID=$SERVER_PID"
  echo "Waiting for server to bind port..."
  sleep 2
  setup_nginx || echo "Warning: nginx setup failed — Node server is still running without a proxy."
}

stop_server_process() {
  local pidfile="$1"
  if [[ -f "$pidfile" ]]; then
    local pid
    pid=$(cat "$pidfile" 2>/dev/null || true)
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      echo "Stopping PID $pid..."
      kill "$pid" || true
      sleep 1
      if kill -0 "$pid" 2>/dev/null; then
        echo "PID $pid did not exit; killing..."
        kill -9 "$pid" || true
      fi
    fi
    rm -f "$pidfile" || true
  fi
}

stop_servers() {
  stop_server_process "$LOG_DIR/server.pid"
  stop_nginx || true
}

start_servers

get_port_for_pid() {
  local pid="$1"
  local logfile="$2"

  # Try ss first
  if command -v ss >/dev/null 2>&1; then
    local line
    line=$(ss -ltnp 2>/dev/null | grep -E "pid=$pid(,|)" | head -n1 || true)
    if [[ -n "$line" ]]; then
      local addr
      addr=$(awk '{print $4}' <<<"$line")
      # extract port (handles IPv4 and IPv6 addresses)
      local port
      port=$(sed -E 's/.*:([0-9]+)$/\1/' <<<"$addr")
      if [[ -n "$port" ]]; then
        echo "$port"
        return 0
      fi
    fi
  fi

  # Fallback to lsof if available
  if command -v lsof >/dev/null 2>&1; then
    local p
    p=$(lsof -Pan -p "$pid" -iTCP -sTCP:LISTEN -n -P 2>/dev/null | awk 'NR>1{print $9}' | sed -E 's/.*:([0-9]+)$/\1/' | head -n1 || true)
    if [[ -n "$p" ]]; then
      echo "$p"
      return 0
    fi
  fi

  # Last-ditch: try parsing logfile for common patterns (vite/node output)
  if [[ -f "$logfile" ]]; then
    local p
    p=$(grep -Eo 'http://[^ ]+:[0-9]+' "$logfile" | sed -E 's/.*:([0-9]+)$/\1/' | head -n1 || true)
    if [[ -n "$p" ]]; then
      echo "$p"
      return 0
    fi
    p=$(grep -Eo ':[0-9]{2,5}' "$logfile" | sed 's/://g' | head -n1 || true)
    if [[ -n "$p" ]]; then
      echo "$p"
      return 0
    fi
  fi

  return 1
}

server_port_found="$(get_port_for_pid "$SERVER_PID" "$LOG_DIR/server.log" || true)"

is_running() { ps -p "$1" >/dev/null 2>&1; }

if is_running "$SERVER_PID"; then
  server_status="running"
else
  server_status="not running"
fi

nginx_status() {
  local nginx_pid_file="$LOG_DIR/nginx.pid"
  if [[ -f "$nginx_pid_file" ]]; then
    local pid
    pid=$(cat "$nginx_pid_file" 2>/dev/null || true)
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      echo "running (PID $pid), port $NGINX_PORT"
      return
    fi
  fi
  echo "not running"
}

echo
echo "Node server (PID $SERVER_PID): $server_status${server_port_found:+, port $server_port_found}"
echo "nginx: $(nginx_status)"
echo "  → http://localhost:${NGINX_PORT}/      (React app, static build)"
echo "  → http://localhost:${NGINX_PORT}/api/  (Node API, proxied to :${SERVER_PORT})"

if [[ "$server_status" != "running" ]]; then
  echo
  echo "---- server log (last 50 lines) ----"
  tail -n 50 "$LOG_DIR/server.log" || true
fi

if [[ "$(nginx_status)" == "not running" ]]; then
  echo
  echo "---- nginx error log (last 50 lines) ----"
  tail -n 50 "$LOG_DIR/nginx-error.log" 2>/dev/null || echo "(no nginx error log yet)"
fi

echo
echo "Logs: $LOG_DIR  (server.log, client-build.log, nginx-access.log, nginx-error.log)"
echo "To stop: kill $SERVER_PID || true  (nginx is managed by this script)"

# Interactive control loop
echo
echo "Control options:"
echo "  r  -> rebuild client, restart Node server and nginx"
echo "  s  -> status"
echo "  l  -> show last 200 lines of all logs"
echo "  q  -> quit script but leave server running"
echo "  k  -> quit script and stop server + nginx"
echo "  h  -> help (show this)"

while true; do
  printf "\ncommand (h for help): "
  if ! read -r cmd; then
    # EOF (e.g. Ctrl-D) — exit while leaving servers running
    echo
    echo "EOF received; leaving servers running and exiting."
    exit 0
  fi
  case "$cmd" in
    r)
      echo "Rebuilding client and restarting..."
      stop_servers
      sleep 1
      run_npm_install_if_needed "$SERVER_DIR" server || true
      run_npm_install_if_needed "$CLIENT_DIR" client || true
      build_client || true
      start_servers
      ;;
    s)
      # refresh status
      if [[ -f "$LOG_DIR/server.pid" ]]; then
        SERVER_PID=$(cat "$LOG_DIR/server.pid" 2>/dev/null || true)
      fi
      if is_running "$SERVER_PID"; then
        server_status="running"
      else
        server_status="not running"
      fi
      server_port_found="$(get_port_for_pid "$SERVER_PID" "$LOG_DIR/server.log" || true)"
      echo "Node server (PID $SERVER_PID): $server_status${server_port_found:+, port $server_port_found}"
      echo "nginx: $(nginx_status)"
      echo "  → http://localhost:${NGINX_PORT}/      (React app, static build)"
      echo "  → http://localhost:${NGINX_PORT}/api/  (Node API)"
      ;;
    l)
      echo "---- server log (last 200 lines) ----"
      tail -n 200 "$LOG_DIR/server.log" || true
      echo
      echo "---- client build log (last 200 lines) ----"
      tail -n 200 "$LOG_DIR/client-build.log" 2>/dev/null || echo "(no client build log yet)"
      echo
      echo "---- nginx error log (last 200 lines) ----"
      tail -n 200 "$LOG_DIR/nginx-error.log" 2>/dev/null || echo "(no nginx error log yet)"
      echo
      echo "---- nginx access log (last 200 lines) ----"
      tail -n 200 "$LOG_DIR/nginx-access.log" 2>/dev/null || echo "(no nginx access log yet)"
      ;;
    q)
      echo "Exiting script and leaving server running. Node PID: $(cat "$LOG_DIR/server.pid" 2>/dev/null || echo 'n/a')"
      exit 0
      ;;
    k)
      echo "Stopping server and nginx, then exiting..."
      stop_servers
      echo "Stopped. Exiting."
      exit 0
      ;;
    h|help)
      echo "Commands: r rebuild+restart, s status, l logs, q quit(leave running), k quit+kill, h help"
      ;;
    "")
      ;;
    *)
      echo "Unknown command: $cmd (h for help)"
      ;;
  esac
done